### ISSUE TITLE
Nova theme for Konsole

### ISSUE THREAD

**Issue by lerouxrgd** [trevordmiller/trevordmiller-website#281]
Just to let you know that I made a Nova color scheme for [Konsole](https://konsole.kde.org/).

Source available [here](https://github.com/lerouxrgd/konsole-color-schemes/blob/master/Nova.colorscheme) and on KDE store [here](https://store.kde.org/p/1311173/).

**Comment by trevordmiller** [comment]
Cool! I’m going to mark this as closed. You are welcome to submit a pull request to the /projects/nova page that documents this in the community plugins section like the other plugins; but the plugin would need to be compiled from “nova-colors” like the other plugins first :)
